### ISSUE TITLE
How can i change the buttons text and/or language? 

### ISSUE THREAD

**Issue by fernandofloresg** [pulsardev/vue-tour#1]
Hi, i'm using vue-tour to create a tour inside a router app, so far its great, so simple, but the main language of the app is spanish and i can't find a way to change the buttons text.

**Comment by mmorainville** [comment]
Hi @fernandofloresg,

To change the language of the buttons you can override the `actions` slot of the `v-step` component.
The documentation is still a work-in-progress but you can find more information on this page:
https://pulsar.gitbooks.io/vue-tour/customizing-the-template.html

Basically at the moment if you want to customize the template of the steps, you have to iterate over the steps in your `v-tour` component. If you use vue-i18n to translate your app, you'll have to do something like this:

```
<v-tour name="myTour" :steps="steps">
  <template slot-scope="tour">
    <transition name="fade">
      <v-step v-if="tour.currentStep === index" v-for="(step, index) of tour.steps" :key="index" :step="step" :previous-step="tour.previousStep" :next-step="tour.nextStep" :stop="tour.stop" :isFirst="tour.isFirst" :isLast="tour.isLast"
      >
        <template>
          <div slot="actions">
            <button @click="tour.stop" v-if="!tour.isLast" class="v-step__button">{{ $t("skipTour") }}</button>
            <button @click="tour.previousStep" v-if="!tour.isFirst" class="v-step__button">{{ $t("previous") }}</button>
            <button @click="tour.nextStep" v-if="!tour.isLast" class="v-step__button">{{ $t("next") }}</button>
            <button @click="tour.stop" v-if="tour.isLast" class="v-step__button">{{ $t("finish") }}</button>
          </div>
        </template>
      </v-step>
    </transition>
  </template>
</v-tour>
```

I know it requires to add a lot of boilerplate if you want to customize your tour, but for now it's the better solution we found to provide a full control over the templates of the steps. We plan to make the customization simpler in later releases, at least for translation purposes.

Hope I've been able to help you!

Regards,
M.

**Comment by fernandofloresg** [comment]
Thanks, keep up the good work ! :+1:

**Comment by nattyluke** [comment]
The code you posted throws a lot of errors in my code like:
`TypeError: "_vm.labels is undefined; can't access its "buttonSkip" property"`
and
`TypeError: "popper is undefined; can't access its "setAttribute" property"`

Can you post a minimum example?

**Comment by mmorainville** [comment]
Hi @nattyluke,

You can check my answer here: https://github.com/pulsardev/vue-tour/issues/53#issuecomment-436209083

It's our mistake, we forgot to update this part of the doc for the v1.1.0.

**Comment by JoedsonGabriel** [comment]
See this example to change the button steps description.
![image](https://user-images.githubusercontent.com/45566621/61880386-31496b00-aecb-11e9-9bd0-a1a0c2a67529.png)

**Comment by deepaksisodiya** [comment]
labels: {
    buttonSkip: i18n.tc("SKIP"),
    buttonPrevious: i18n.tc("PREVIOUS"),
    buttonNext: i18n.tc("NEXT"),
    buttonStop: i18n.tc("FINISH"),
  },

**Comment by quroom** [comment]
If you guys change locale in realtime, use computed property for labels.
If using labels in data, it's not responsible in realtime.

**Comment by wladston** [comment]
I did as @quroom suggested, and it works!
