### ISSUE TITLE
Logs to console for each step

### ISSUE THREAD

**Issue by BWagener** [pulsardev/vue-tour#101]
Hello,

I've noticed with 1.2 there is log output for each step such as "[Vue Tour] Highlight is disabled for .v-step[id="b4820cfe"]" with no apparent way to disable it.

**Comment by HZooly** [comment]
@BWagener, you are right, there are some logs in the library that are currently not disablable. That could be a nice global configuration @mmorainville

**Comment by mmorainville** [comment]
Indeed, we'll get rid of them, maybe in a bugfix release so it comes out faster.
