### ISSUE TITLE
welcome screen

### ISSUE THREAD

**Issue by ASVBPREAUBV** [pulsardev/vue-tour#104]
Is is possible to start a tour with a welcome screen?
Meaning the first step of the tour should just be a center/center window.

**Comment by HZooly** [comment]
Hi @ASVBPREAUBV. I'm not sure to understand what you want to do.
Could you provide an example?

**Comment by ASVBPREAUBV** [comment]
@HZooly Thanks for the quick reply and sorry for the bad explanation. I would like to show steps of the tour that are not associated with a DOM-Element.

**Comment by HZooly** [comment]
Ok I understand! There's currently a PR #51 that do that, we'll merge it as soon as possible.

**Comment by ASVBPREAUBV** [comment]
Thanks
