### ISSUE TITLE
stopping tour after triggering a step modal 

### ISSUE THREAD

**Issue by marouatnk** [pulsardev/vue-tour#105]
Hello I want to trigger a modal by stopping the tour on my componenent and starting another tour when my modal is on view : 

     myCustomNextStepCallback(currentStep) {
            if (currentStep === 3 && !this.$tours.myTour.steps[currentStep ].finished) {
               this.$tours.myTour.steps[currentStep ].finished  = true
               this.$tours['myTour'].stop()
               this.spreadDialog = true
           }
    },

by doing this the modal pops up but in the back my first tour starts again . so this leaves me with two tours running at the same time ! 
is there a possibility to stop a tour !!

**Comment by sylver-john** [comment]
Hi @marouatnk , First, how do you start the first tour ? Did you specify 2 different names for the tours ?
To clarify : You have a tour "myTour", you run it then you want to trigger a modal and stop the current tour "myTour" and then starting another tour, that's right ?

**Comment by marouatnk** [comment]
Hi , yes you got it right . 
Well my modal is in a separate vue component that's why I kept the same name for both tours actually. Would naming them differently  solve the problem you say ?

**Comment by sylver-john** [comment]
@marouatnk Well I let you find out :)

**Comment by mmorainville** [comment]
Closing the issue as the problem seems to be solved.
