### ISSUE TITLE
Ability to Highlight the target div

### ISSUE THREAD

**Issue by darkscript** [pulsardev/vue-tour#11]
It would be great to be able to highlight the target div as deemonstrated in image below 
![image](https://user-images.githubusercontent.com/13992858/38011248-5b2b84e6-3265-11e8-816d-998ed6ae1bc5.png)

**Comment by mmorainville** [comment]
Hi @darkscript,

It's a planned feature actually, but you did well opening an issue for it as now we can see that this feature is needed.
We'll try to add this soon, for v1.1.0 hopefully.
But it's not a small feature and there is many way to do it. It would also be nice to have some cool animations when the backdrop is moving from one element to another.

React Joyride uses a div with a z-index but I find that http://kamranahmed.info/driver is doing it better: it simply uses a canva and cut through it to hightlight the element.

We'll see but what's sure is that it's on our roadmap!

**Comment by darkscript** [comment]
ok, thanks much for this great extension and we will be happy to see the improvements.

**Comment by joffreyBerrier** [comment]
thx @mmorainville this is a great extension, i can not wait to see this

**Comment by joffreyBerrier** [comment]
hi @mmorainville can you give me a deployment date ?

**Comment by thinhnguyendn93** [comment]
@joffreyBerrier I customed vue-tour in this code below to highlight targets.
It run well on my side.
[Tour.zip](https://github.com/pulsardev/vue-tour/files/2057919/Tour.zip)

**Comment by darkscript** [comment]
@joffreyBerrier thanks for sharing, I will try it

**Comment by roelVerdonschot** [comment]
Is there any progress on this issue?

**Comment by mmorainville** [comment]
Hi all,

Sorry we haven't had the time to dig into this issue yet. I'll take a look on @thinhnguyendn93 code (if it's ok for you?). Don't hesitate to make a PR if you think you have something working well.

We want to do this right and this means supporting a resize of the window but depending on the solution used to implement this it could mean listening to the `resize` window event and that's not so great...

**Comment by perez0711** [comment]
:star:

**Comment by mmorainville** [comment]
Hi everyone,

It has been merged and is now available in vue-tour 1.2.x !
The documentation for this new feature is here: https://github.com/pulsardev/vue-tour/wiki/Features.

**Comment by Adrek** [comment]
Great

**Comment by Adrek** [comment]
greats

**Comment by Adrek** [comment]
> Hi everyone,
> 
> It has been merged and is now available in vue-tour 1.2.x !
> The documentation for this new feature is here: https://github.com/pulsardev/vue-tour/wiki/Features.

It's great, thanks. And if you add this rule in your global style works like a dimmer.
.v-tour__target--highlighted {
    box-shadow: 0 0 0 3000px rgba(0,0,0,.4);
    border-radius: 5px;
}

**Comment by darkscript** [comment]
thanks for adding this option

**Comment by Outpox** [comment]
Thanks for your contribution and sorry it took us so long to release it.

**Comment by danzt** [comment]
> @joffreyBerrier I customed vue-tour in this code below to highlight targets. It run well on my side. [Tour.zip](https://github.com/pulsardev/vue-tour/files/2057919/Tour.zip)

This is perfect, but is with Jquery :( It would be nice if it was only with
