### ISSUE TITLE
Hashed attributes in css

### ISSUE THREAD

**Issue by dennismeissner** [pulsardev/vue-tour#110]
It looks like you pushed the css with generated hashed attributes:

```
.v-step .v-step__arrow[data-v-7c9c03f0] {
.v-step[data-v-7c9c03f0]
...
```

which does not apply the styles at all. Can you fix this soon plz?

**Comment by dennismeissner** [comment]
nvm, had something in cache

**Comment by Outpox** [comment]
Hehe no worry.  
You had me scared when I saw the notification at first tough :eyes:
