### ISSUE TITLE
Tour over two different pages 

### ISSUE THREAD

**Issue by labionabazi** [pulsardev/vue-tour#112]
I am not able to make a vue tour over two components. As example when i start the tour on the landing page and then i want to show to users where the new feature is implemented i am not able to switch the pages and show the next step on the right place because the step is loading faster as the new page is rendering.

**Comment by yuters** [comment]
I think this is already discussed here https://github.com/pulsardev/vue-tour/issues/37

**Comment by mmorainville** [comment]
Hi @labionabazi,

Actually there even is an example here: https://github.com/pulsardev/vue-tour/issues/12.
