### ISSUE TITLE
返回上一步问题

### ISSUE THREAD

**Issue by chenafk** [pulsardev/vue-tour#118]
大多数情况下不需要上一步按钮的，注释、删除、设置false，都会留下一个空的div，点击依然会到上一步提示。

**Comment by HZooly** [comment]
Hi @chenafk, I used Translate to understand what is your issue about. For the future, please report issues, PR or anything in English, we do not speak this language at Pulsar.

What do you suggest for avoiding this empty div?

**Comment by chenafk** [comment]
@tour默认按钮有上一步跟下一步，

> 嗨@chenafk，我用翻译来了解您的问题。为了将来，请报告问题，PR或任何英语，我们在Pulsar不讲这种语言。
> 
> 您对避免此空div有何建议？

Hello, there is a previous step for Vue tour guidance by default, but I don't see the official way to delete this button

**Comment by chenafk** [comment]
> Hi @chenafk, I used Translate to understand what is your issue about. For the future, please report issues, PR or anything in English, we do not speak this language at Pulsar.
> 
> What do you suggest for avoiding this empty div?
