### ISSUE TITLE
Vue Tour is not properly working on Safari

### ISSUE THREAD

**Issue by Djshn** [pulsardev/vue-tour#119]
I have a basic implementation of Vue-Tour that works fine on Chrome but it resizes the starting element (v-card) on Safari. I am also using Vuetify. Is this a bug?

**Comment by HZooly** [comment]
Hi @Djshn, can you please provide an example ? I'm unable to reproduce the bug on Safari, everything is working well on my side.

**Comment by HZooly** [comment]
@Djshn any news on this? Or I can close the issue?
