### ISSUE TITLE
每个步骤的样式样式可以添加自定义的class

### ISSUE THREAD

**Issue by cozhaomeizhen** [pulsardev/vue-tour#126]
每个步骤的样式样式可以添加自定义的class，每个步骤的样式不一样

**Comment by HZooly** [comment]
Hello @cozhaomeizhen, I'm not sure to fully understand what you say, because no one of us can read chinese.
But if I'm right, you want to customize each step style.

This is possible by using slots of V-Step component : header, content and actions.
