### ISSUE TITLE
Option To disable/enable certain keyboard navigations. 

### ISSUE THREAD

**Issue by bsl333** [pulsardev/vue-tour#128]
I would like to be able to use the keyboard to control the tour, but I would like to be able to disable ESC from being used. I looked thru the source code and it doesn't seem that this ability is included in vue-tour. Is there a specific reason why? If not, I can create a PR to add this feature, and can generalize to include ⬅️ and ➡️

**Comment by HZooly** [comment]
Hi @bsl333, indeed there's no way to select individually keyboard controls.
It could be a nice feature, but we don't want to break anything for users that already use the configuration option.
Let's talk about this here with @mmorainville, @Outpox and me 😄

**Comment by bsl333** [comment]
Hello @HZooly and all,

So I was able to implement the feature and it shouldn't have any breaking changes. I followed the same implementation pattern as the `enabledButtons` feature. 

Here's the bulk of the PR. 

```javascript
    handleKeyup (e) {
      if (this.customOptions.debug) {
        console.log('[Vue Tour] A keyup event occured:', e)
      }
      switch (e.keyCode) {
        case KEYS.ARROW_RIGHT:
          this.isKeyEnabled('ARROW_RIGHT') && this.nextStep() // Changed
          break
        case KEYS.ARROW_LEFT:
          this.isKeyEnabled('ARROW_LEFT') && this.previousStep() // Changed
          break
        case KEYS.ESCAPE:
          this.isKeyEnabled('ESC') && this.stop() // Changed
          break
      }
    },
    
   // added below
    isKeyEnabled (key) {
      const { enabledKeys } = this.customOptions
      return enabledKeys.hasOwnProperty(key) ? enabledKeys[key] : true
    }

  // constants.js DEFAULT_OPTIONS:
  enabledKeys: {
    ESCAPE: true,
    ARROW_RIGHT: true,
    ARROW_LEFT: true
  },
```

The key names in enabled keys follow the same names as in the `KEYS` constant. I can change them to be more JS-friendly, something like `esc`, `arrowLeft` and `arrowRight`. 

Let me know what you think or if you'd like me to create a PR. 

Thanks.

**Comment by HZooly** [comment]
@mmorainville any thoughts about this?
For me, it doesn't break anything and brings a better control on Vue Tour keys.

**Comment by mmorainville** [comment]
Hi all,

It looks good to me, thanks a lot for the contribution!
The only thing would be the naming of the keys as we already discussed in the Vue Tour 2 proposal issue we plan to go full camelCase to be indeed more JS-friendly.
But as you mentionned we already use those constants-like naming for keys so it shouldn't be a problem! 🙂

**Comment by bsl333** [comment]
Hi @mmorainville, 

Ok, I'll keep the naming as is (ALL_CAPS), and I'll submit the PR in the next day or so. 
Glad to help out!
