### ISSUE TITLE
Add cookie for not repeating the tour

### ISSUE THREAD

**Issue by mgarcia96** [pulsardev/vue-tour#130]
Hey there, I propose a feature that consist in create a cookie. Because normally you only want to complete the tour one time. When you complete a tour the cookie will save that you won't see the tour again

**Comment by HZooly** [comment]
Vue Tour aims to be minimalist as possible.

I think this is on your side to decide if tour has to be started or not, by using cookies, localStorage, backend data or anything you want.

**Comment by flyfishwv** [comment]
so is your suggestion to add a checkbox in the tour div and then store the users preference? how do I add elements to the main tour element without forking the project? I've tried various implementations with no luck so far. Thank you for your time and for the vue tour!
