### ISSUE TITLE
How to properly install? 

### ISSUE THREAD

**Issue by osmelg** [pulsardev/vue-tour#136]
I'm following the exact installation steps and I got a can't found vue-tour component. Please update the installation process with these step. By the way, how can it be fixed?

**Comment by HZooly** [comment]
Can you check if you don't miss any import?

```js
import Vue from 'vue'
import App from './App.vue'
import VueTour from 'vue-tour'

require('vue-tour/dist/vue-tour.css')

Vue.use(VueTour)

new Vue({
  render: h => h(App)
}).$mount('#app')
```

**Comment by osmelg** [comment]
i restarted the app and it work, so, the library work, thanks!
