### ISSUE TITLE
Source without bundler?

### ISSUE THREAD

**Issue by craigg75** [pulsardev/vue-tour#138]
We don't use any bundlers, do you a version without bundlers? Thanks.

**Comment by mmorainville** [comment]
Hi @craigg75,

Normally if use use the UMD build it should work just fine.

```html
<script src="./vue-tour.umd.min.js"></script>
<link rel="stylesheet" href="./vue-tour.css">
```

https://github.com/pulsardev/vue-tour/tree/master/dist
