### ISSUE TITLE
Transition duration

### ISSUE THREAD

**Issue by alinurr1** [pulsardev/vue-tour#143]
Hello!

I didn't find an option to somehow modify the transition effect between steps?
Specifically, I wanted to know if there is a way to make a transition "smoother".

Thank you

**Comment by HZooly** [comment]
Hello!

Are you talking about scroll effect or CSS transition at step display?

**Comment by alinurr1** [comment]
CSS transition at step display

**Comment by HZooly** [comment]
You can simply [customize the steps template](https://github.com/pulsardev/vue-tour/wiki/Customizing-the-Template) and use [Vue Transitions](https://vuejs.org/v2/guide/transitions.html) to make it behave as you want.

**Comment by alinurr1** [comment]
Thank you, this seems to solve my problem

**Comment by ricky11** [comment]
In order to use vue -transition, the v-tour would need a conditional v-if?  how to add a transition without a v-if?  And what is the current transition?
