### ISSUE TITLE
Are there plans to support IE11?

### ISSUE THREAD

**Issue by nambiarn** [pulsardev/vue-tour#146]
**Describe the bug**
The css doesn't render in IE11

**Comment by HZooly** [comment]
Do you have a reproducible example? 

We didn't encountered any issue with IE11.

**Comment by nambiarn** [comment]
Here are the screenshots: 
Chrome
<img width="384" alt="Screen Shot 2020-08-07 at 8 23 13 AM" src="https://user-images.githubusercontent.com/18222457/89649999-4a7b4a80-d887-11ea-9b4d-750ab1a6b9e3.png">

IE 11:
<img width="374" alt="Screen Shot 2020-08-07 at 8 23 19 AM" src="https://user-images.githubusercontent.com/18222457/89650027-5961fd00-d887-11ea-98eb-479dd9a00bf6.png">

I followed the documentation to the tee.

**Comment by mmorainville** [comment]
Hi @nambiarn,

I've checked and it's working fine on the landing page:
![image](https://user-images.githubusercontent.com/1155743/89660036-0c0a7d80-d8d1-11ea-964a-61d7f52fcc59.png)

So it seems indeed to be a problem with your configuration as we already support IE11.
I suggest we review your PostCSS output file and check if the Vue Tour classes are defined.

You can find them at the bottom of the components:
https://github.com/pulsardev/vue-tour/blob/master/src/components/VStep.vue
https://github.com/pulsardev/vue-tour/blob/master/src/components/VTour.vue

**Comment by nambiarn** [comment]
Thank you for your help @HZooly and @mmorainville!
