### ISSUE TITLE
Can you support modifying the background color （expect highlight element）

### ISSUE THREAD

**Issue by sc8816** [pulsardev/vue-tour#147]
I want to add a mask to cover other elements and only show the highlighted elements

**Comment by HZooly** [comment]
You can use the `highlight` option : https://github.com/pulsardev/vue-tour/wiki/Features#highlight-v12x

**Comment by sc8816** [comment]
> You can use the `highlight` option : https://github.com/pulsardev/vue-tour/wiki/Features#highlight-v12x

What I mean is that I want to modify the background color of the element that is not highlighted, and add a mask layer to the whole. I directly add the background color to the element (v-tour--active) and it cannot take effect.

**Comment by HZooly** [comment]
I see. Unfortunately I believe this is currently impossible to achieve this.
You have to wait for net version of Vue Tour, or do some CSS tricks around your V-Tour component.

**Comment by muners** [comment]
how about this

```
<template lang="pug">
v-tour(
  :name="tour_id",
  :steps="steps",
  :options="tourOptions",
  :callbacks="tourCallbacks"
)


</template>

<script>
import { mapState } from 'vuex'

export default {
  components: {
  },
  props: {
    tour_id: {type: String, default: "myTour"},
    steps: Array,
  },
  data() {
    return {
      tourOptions: {
        labels: {
          buttonSkip: "スキップ",
          buttonPrevious: "戻る",
          buttonNext: "次へ",
          buttonStop: "終了",
        },
      },
      tourCallbacks: {
        onStart: this.tourOnStart,
        onSkip: this.tourOnFinish,
        onFinish: this.tourOnFinish,
        onStop: this.tourOnFinish,
      },
    }
  },
  async mounted() {
  },
  computed: {
  },
  watch: {
    steps (val, old) {
      this.steps = val
    }
  },
  methods: {
    tourOnStart(){
      console.log("tourOnStart")
      const currency = document.querySelector(".v-tour");
      currency.classList.add("v-tour-active");
    },
    tourOnFinish(){
      console.log("tourOnFinish")
      const currency = document.querySelector(".v-tour");
      currency.classList.remove("v-tour-active");
    },
  },
}
</script>

<style lang="scss">
.v-tour-active::before {
  content: "";
  position: fixed;
  background-color: #8080807d;
  width: 100vw;
  height: 100vh;
  top: 1px;
  left: 0;
  z-index: 20;
}
</style>

```

**Comment by ZonaHex** [comment]
> how about this
> 
> ```
> <template lang="pug">
> v-tour(
>   :name="tour_id",
>   :steps="steps",
>   :options="tourOptions",
>   :callbacks="tourCallbacks"
> )
> 
> 
> </template>
> 
> <script>
> import { mapState } from 'vuex'
> 
> export default {
>   components: {
>   },
>   props: {
>     tour_id: {type: String, default: "myTour"},
>     steps: Array,
>   },
>   data() {
>     return {
>       tourOptions: {
>         labels: {
>           buttonSkip: "スキップ",
>           buttonPrevious: "戻る",
>           buttonNext: "次へ",
>           buttonStop: "終了",
>         },
>       },
>       tourCallbacks: {
>         onStart: this.tourOnStart,
>         onSkip: this.tourOnFinish,
>         onFinish: this.tourOnFinish,
>         onStop: this.tourOnFinish,
>       },
>     }
>   },
>   async mounted() {
>   },
>   computed: {
>   },
>   watch: {
>     steps (val, old) {
>       this.steps = val
>     }
>   },
>   methods: {
>     tourOnStart(){
>       console.log("tourOnStart")
>       const currency = document.querySelector(".v-tour");
>       currency.classList.add("v-tour-active");
>     },
>     tourOnFinish(){
>       console.log("tourOnFinish")
>       const currency = document.querySelector(".v-tour");
>       currency.classList.remove("v-tour-active");
>     },
>   },
> }
> </script>
> 
> <style lang="scss">
> .v-tour-active::before {
>   content: "";
>   position: fixed;
>   background-color: #8080807d;
>   width: 100vw;
>   height: 100vh;
>   top: 1px;
>   left: 0;
>   z-index: 20;
> }
> </style>
> ```

I tried the same thing, but the highlight component itself is also covered by the background color. I want it to still be highlighted. Do you have any idea :D?
