### ISSUE TITLE
v-for and v-if on v-step warning

### ISSUE THREAD

**Issue by Skylercrane23** [pulsardev/vue-tour#148]
**Describe the bug**
When customizing the template docs show a v-for and v-if on the v-step component. Doing this throws some warnings and is generally bad practice in the Vue ecosystem. 

**To Reproduce**
Docs example of customizing the template

**Expected behavior**
There should be a way to add the v-if on the step without it being on the same element as the v-for.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by nickgayo12** [comment]
Also used this one, and its giving errors to.

**Comment by Dave3of5** [comment]
The v-for is unnecessary something like this will work:

```
 <v-tour name="myTour" :steps="steps">
    <template slot-scope="tour">
      <transition name="fade">
        <v-step
          :step="tour.steps[tour.currentStep]"
          v-if="tour.steps[tour.currentStep]"

          :previous-step="tour.previousStep"
          :next-step="tour.nextStep"
          :stop="tour.stop"
          :skip="tour.skip"
          :is-first="tour.isFirst"
          :is-last="tour.isLast"
          :labels="tour.labels"
        >


          <template>
            <div slot="actions" v-if="tour.currentStep === 0">
              <button @click="tour.nextStep" class="btn btn-primary">Next</button>
            </div>
            <div slot="actions" v-else-if="tour.currentStep === tour.steps.length">
              <button @click="tour.previousStep" class="btn btn-primary">Previous</button>
              <button @click="tour.stop" class="btn btn-primary">Finish</button>
            </div>
            <div slot="actions" v-else>
              <button @click="tour.previousStep" class="btn btn-primary">Previous</button>
              <button @click="tour.nextStep" class="btn btn-primary">Next</button>
            </div>
          </template>
        </v-step>
      </transition>
    </template>
  </v-tour>
```

You can change the actions slot to have whatever custom button template you want but the important part here is that the tour v-step doesn't have a v-for.

Hopefully that helps as I struggled with this as well.

**Comment by Skylercrane23** [comment]
` <v-tour :steps="steps" :options="myOptions" :callbacks="myCallbacks" name="btcSendTour">
            <template slot-scope="tour">
                <transition name="fade" mode="out-in">
                    <v-step
                        :step="tour.steps[tour.currentStep]"
                        v-if="tour.steps[tour.currentStep]"
                        :previous-step="tour.previousStep"
                        :next-step="tour.nextStep"
                        :stop="tour.stop"
                        :skip="tour.skip"
                        :is-first="tour.isFirst"
                        :is-last="tour.isLast"
                        :labels="tour.labels"
                    >
                        <template>
                            
                            <div slot="actions" class="flex items-center justify-center">
                                <button v-if="tour.currentStep === 0" @click="tour.skip" class="btn btn-white">
                                    Skip
                                </button>
                                <button v-if="tour.currentStep > 0" @click="tour.previousStep" class="btn btn-white">
                                    Previous
                                </button>
                                <button v-if="tour.currentStep !== 4" @click="tour.nextStep" class="ml-4 btn btn-blue">
                                    Next
                                </button>
                                <button @click="tour.finish" v-else class="ml-4 btn btn-blue">Finish</button>
                            </div>
                        </template>
                    </v-step>
                </transition>
            </template>
        </v-tour>`

@Dave3of5 Doing this gets rid of the warning, but now the targets that my steps are too don't work. They all show up in the same place even though my target div's with IDs are in different locations.

**Comment by Skylercrane23** [comment]
@Dave3of5 Doing this gets rid of the warning, but now the targets that my steps are too don't work. They all show up in the same place even though my target div's with IDs are in different locations.

**Comment by Dave3of5** [comment]
@Skylercrane23 Yes just noticed this too bah. I can't figure out why it's not working to be honest.

**Comment by Dave3of5** [comment]
Ok I figured it out. Vue Tour uses the mounted method to create the popper.js popup so you need to force a re-render when the current step changes. The easiest way to do that it with a Key on the tour step so if you add a key you will get something like:

```
 <v-tour name="myTour" :steps="steps">
    <template slot-scope="tour">
      <transition name="fade">
        <v-step
          :step="tour.steps[tour.currentStep]"
          v-if="tour.steps[tour.currentStep]"
          :key="tour.currentStep"
          :previous-step="tour.previousStep"
          :next-step="tour.nextStep"
          :stop="tour.stop"
          :skip="tour.skip"
          :is-first="tour.isFirst"
          :is-last="tour.isLast"
          :labels="tour.labels"
        >


          <template>
            <div slot="actions" v-if="tour.currentStep === 0">
              <button @click="tour.nextStep" class="btn btn-primary">Next</button>
            </div>
            <div slot="actions" v-else-if="tour.currentStep === tour.steps.length">
              <button @click="tour.previousStep" class="btn btn-primary">Previous</button>
              <button @click="tour.stop" class="btn btn-primary">Finish</button>
            </div>
            <div slot="actions" v-else>
              <button @click="tour.previousStep" class="btn btn-primary">Previous</button>
              <button @click="tour.nextStep" class="btn btn-primary">Next</button>
            </div>
          </template>
        </v-step>
      </transition>
    </template>
  </v-tour>
```

For the example @Skylercrane23 gives it's:

```
    <v-tour :steps="steps" :options="myOptions" :callbacks="myCallbacks" name="btcSendTour">
            <template slot-scope="tour">
                <transition name="fade" mode="out-in">
                    <v-step
                        :step="tour.steps[tour.currentStep]"
                        v-if="tour.steps[tour.currentStep]"
                        :key="tour.currentStep"
                        :previous-step="tour.previousStep"
                        :next-step="tour.nextStep"
                        :stop="tour.stop"
                        :skip="tour.skip"
                        :is-first="tour.isFirst"
                        :is-last="tour.isLast"
                        :labels="tour.labels"
                    >
                        <template>
                            <div slot="content">
                                <div v-if="tour.currentStep === 0">Recipient BTC Wallet</div>
                                <div v-if="tour.currentStep === 1">BTC Amount</div>
                                <div v-if="tour.currentStep === 2">Preview Send</div>
                                <div v-if="tour.currentStep === 3">TwoStep Authentication</div>
                                <div v-if="tour.currentStep === 4">Success</div>
                            </div>
                            <div slot="actions" class="flex items-center justify-center">
                                <button v-if="tour.currentStep === 0" @click="tour.skip" class="btn btn-white">
                                    Skip
                                </button>
                                <button v-if="tour.currentStep > 0" @click="tour.previousStep" class="btn btn-white">
                                    Previous
                                </button>
                                <button v-if="tour.currentStep !== 4" @click="tour.nextStep" class="ml-4 btn btn-blue">
                                    Next
                                </button>
                                <button @click="tour.finish" v-else class="ml-4 btn btn-blue">Finish</button>
                            </div>
                        </template>
                    </v-step>
                </transition>
            </template>
        </v-tour>
```

This is what the original example is trying to do is force a render when the current step changes.

**Comment by Skylercrane23** [comment]
@Dave3of5  awesome this works perfectly, thanks!
