### ISSUE TITLE
Scrolling to the bottom of the page whenever clicking to the next step

### ISSUE THREAD

**Issue by jtoddp14** [pulsardev/vue-tour#152]
**Describe the bug**
Whenever clicking or starting the tour on the current component, the window will scroll away from the target and go to the bottom of that page. This repeats with every step forward or backwards. It will not scroll to the target, it will instead scroll to the bottom of the page, but the v-tour popup will be placed correctly at the top.

**To Reproduce**
1. Start tour, initial load will appear at the top of the page, the window will scroll to the bottom of the page
2. Scroll to the top of the page to click "next", the next step will appear and the page will scroll again.

**Expected behavior**
The window would scroll to where the v-tour step occurs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.102

https://codepen.io/jtoddp14/pen/ExKGVWK - doesnt work but you can see how everything is written

**Comment by mmorainville** [comment]
Hi @jtoddp14,

It's weird we never experienced such a behavior when testing. It certainly has something to do with the auto-scroll feature though. Have you tried to disable it? (https://github.com/pulsardev/vue-tour/wiki/Features#disable-scroll-between-steps)

```
{
  target: '#v-step-0',
  content: `Discover <strong>Vue Tour</strong>!`,
  params: {
    enableScrolling: false
  }
}
```

**Comment by mmorainville** [comment]
Really weird, especially given that if you don't set a custom duration or offset, we also use scrollIntoView().
https://github.com/pulsardev/vue-tour/blob/master/src/components/VStep.vue#L126

I'll close the issue for now, as the issue seems to be linked to your project setup, but we'll keep an eye on it when migrating the lib to Vue 3.
