### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by vikaskedia** [pulsardev/vue-tour#153]
Excellent piece of software. Better then intro.js and I am using it at  [Vue Emr](https://github.com/savantcare/emr)

Please fix this typo

https://github.com/pulsardev/vue-tour/wiki/Customizing-the-Template

The following line has been repeated twice:
 :labels="tour.labels"
 :labels="tour.labels"

**Comment by HZooly** [comment]
Thanks for your feedback!
