### ISSUE TITLE
Suggestions for Vue-3 Update

### ISSUE THREAD

**Issue by jd-0001** [pulsardev/vue-tour#154]
As we are expecting a new release and plugin might get new API. I would like to suggest few things:

1. Is it possible to add an overlay feature to eliminate distraction from certain (selected in tour step) element
2. SCSS variables to override style

If I can't see this in next update, it's totally fine. This is just my thoughts.

Regards.

**Comment by mmorainville** [comment]
Hi @jd-0001,

Thanks for your suggestions, it's always nice to have some external inputs!

Concerning your points though, 1. is already implemented (see https://github.com/pulsardev/vue-tour/wiki/Features#highlight-v12x) but we'll try to improve it in the Vue 3 version.

And for 2. we would like to keep vue-tour as simple and lightweight as possible, this means skipping everything that is not *really* necessary to make a guided tour.
It's certainly true that customization is a very needed feature for this kind of plugin, but as for now, all classes can be overriden in the parent app (and you can also override the HTML!).
But I see what you mean, you would want simple variables to override, let's say, the padding, margin, background colors, etc.?

While it would certainly be useful, we don't plan to add SCSS to our build process. But we could try other alternatives such as CSS variables.

Regards.

**Comment by valpet** [comment]
How about exposing slots instead so one can implement tours using one's UI framework of choice, for example Vuetify etc?

**Comment by jd-0001** [comment]
@mmorainville Thanks for the response. Yes, right now I am just targeting color, bgColor, padding, margin, etc.

**Comment by jd-0001** [comment]
Hi @valpet,

have you tried the below guide:
https://github.com/pulsardev/vue-tour/wiki/Customizing-the-Template

I think this is what you are looking for and what I am currently using.

**Comment by gwenker** [comment]
Could be interesting to implement a system of retry with timeout when vue-tour looking for the target.
Like Cypress : https://docs.cypress.io/guides/core-concepts/retry-ability.html

Could be really helpfull when you have to interact with router or with async process.

**Comment by jd-0001** [comment]
Hi, I tried Highlight option in this package and sorry if I misguided you. Actually I was refering to highlight element using overlay.

like below: [Tour Page](https://pixinvent.com/demo/vuexy-html-bootstrap-admin-template/html/ltr/vertical-menu-template/ext-component-tour.html)

So, the tour set overlay on all elements except the one which is targeted.

Regards.
