### ISSUE TITLE
Prevent click but not hover of highlighted area items

### ISSUE THREAD

**Issue by jonalxh** [pulsardev/vue-tour#158]
**Describe the bug**
Im trying to make a tour in my app which has a lot of buttons in each step, I want the user to hover the buttons to know what they do when a tooltip is shown, but I dont want to let the user click the items, because they will trigger different actions.

I've tried disabling pointer events with CSS but any event is fired and this is not my need. I've tried also to trigger an off("click"), off() and unbind events inside the highlighted area when tour is started, but it neither  work:

```
onTourStart() {
                       setTimeout(() => {
				$(".v-tour__target--highlighted").off();
				$(".v-tour__target--highlighted").unbind();
				$(".v-tour__target--highlighted *").off();
				$(".v-tour__target--highlighted *").unbind();
			}, 1000)
}
```

Is there a way to achieve it?

**Comment by HZooly** [comment]
There's no perfect solution for this, you have to write custom code when Tour is running.
It could be a mask around the highlighted element, where you disable any click on it with `pointer-events: none`.
