### ISSUE TITLE
Dynamic step

### ISSUE THREAD

**Issue by myAccount11** [pulsardev/vue-tour#167]
when step target element not defined it can skip this step, example we have 5 step and for 3 step target element not defined then it can automatically change to 4 step

**Comment by mmorainville** [comment]
Hi @myAccount11,

What would be the use-case?
And actually I've just merged a PR (https://github.com/pulsardev/vue-tour/pull/51) that handles the steps with no target as "sticky step", a step that is bound to no target and floats in the center of the screen.
