### ISSUE TITLE
Missing documentation for before() callback

### ISSUE THREAD

**Issue by Ragnar-Oock** [pulsardev/vue-tour#173]
for a project I'm on I need to open a dropdown before proceeding to the next step in the tour, I found that the before() callback was added for this specific use case in 1.5.0 but I could not find any documentation about how it works.

**Comment by Ragnar-Oock** [comment]
found it on the [npm page](https://www.npmjs.com/package/vue-tour#before-ui-step-functions), it would be great to have it on the wiki page too

**Comment by mmorainville** [comment]
Hi @Ragnar-Oock,

Thanks for noticing this, it's done: https://github.com/pulsardev/vue-tour/wiki/Features.
