### ISSUE TITLE
.v-step z-index

### ISSUE THREAD

**Issue by CromonMS** [pulsardev/vue-tour#18]
Hi,

Really glad to have found this, it's helping me a lot! Thanks.

Found a bug, I am using Bulma.io for styles, so not sure if it's a compatibility issue or not.

Basically I get a display problem with the steps, and it's fixed after adding z-index: 10000 to .v-step[data-v-570be51d] see pics.

### Without z-index

![vue-tour-no-z-index](https://user-images.githubusercontent.com/5735921/39262305-f6df49e2-48b6-11e8-9553-ffec75d52533.png)

### With z-index

![vue-tour-z-index-10000](https://user-images.githubusercontent.com/5735921/39262306-f6f9da32-48b6-11e8-87b9-e4859f74a634.png)

Not sure if this is something you'd like to add to the css in the library. But thought I'd let you know.

**Comment by Outpox** [comment]
Hey! 
Thanks for the feedback :smiley: 
This is a fair point but I may see issues when using an overlay on a page with such an addition.
Also we prefer to let the users style the elements themselves and so the steps use the simple `v-step` class.

Feel free to re-open the issue if you want to discuss that point a bit more.

**Comment by CromonMS** [comment]
True, it could have other implications in the future (I've already tweaked it down to ```z-index: 39;``` because of a modal in the same form!)

I'll just stick to styling the ```.v-step``` for now :)
