### ISSUE TITLE
Suggestion :  Can we add overlay effect in this library

### ISSUE THREAD

**Issue by Meet132** [pulsardev/vue-tour#180]
I have a requirement where I need to add an overlay effect. Does this library provide this feature?  If no, would it be possible to customize it?

(https://cdn.ourcodeworld.com/public-media/gallery/gallery-5854ffe466ef1.png)

**Comment by HZooly** [comment]
We provide this CSS solution for an overlay effect, but you can implement your own : https://github.com/pulsardev/vue-tour/wiki/Features#customization
