### ISSUE TITLE
Spotlight effect in Vue Tour

### ISSUE THREAD

**Issue by Gabvo94** [pulsardev/vue-tour#182]
Hi All

Is there an easy way to highlight a section of the screen, and grey out the rest? Basically adding a spotlight effect?

Thank you!

**Comment by mmorainville** [comment]
Hi @Gabvo94,

Yes there is! Here is the documentation for it: https://github.com/pulsardev/vue-tour/wiki/Features#highlight-v12x.
You can also customize the CSS of the backdrop to make it fill the entire screen (see https://github.com/pulsardev/vue-tour/wiki/Features#customization).
