### ISSUE TITLE
I want to hide a step like i have multiple steps v-step-1 to v-step-10 I want to hide particular 2-3 in between  

### ISSUE THREAD

**Issue by debayan-ghosh** [pulsardev/vue-tour#183]
steps: [
        {
          target: "#v-step-0", // We're using document.querySelector() under the hood
          header: {
            title: "XXX....",
          },
          params: {
            placement: "right",
          },
          content: `xxx...`,
        },
        {
          target: "#v-step-1",
          header: {
            title: "XXX.....",
          },
          params: {
            placement: "right",
          },
          content:
            "XXX....",
        }
]

**Comment by mmorainville** [comment]
Hi @debayan-ghosh,

There is several solutions to this problem.
You can either:
- Make your steps array reactive and remove the steps you want to hide, then readd it when you need them
- Use the before/after hooks and redirect for example to step 4 from step 1

There is no option to hide a step because this can be handled by different ways and is not relevant for common use cases.

**Comment by debayan-ghosh** [comment]
Hi Can you show me an example how to do it?

**Comment by ricky11** [comment]
"Use the before/after hooks and redirect for example to step 4 from step 1"

how do you redirect?

**Comment by quroom** [comment]
When the next and prev called, Check the condition matched.
And then you can ignore steps that are matchec with condition.

I did like this.
```

    nextStepTour(currentStep) {
      console.log("next");
      if (currentStep == 0) {
        if (this.$attrs.has_profile) {
          this.$nextTick(() => {
            const tour = this.$tours["myTour"];
            tour.currentStep = currentStep + 2;
          });
        }
      }
    },
    previousStepTour(currentStep) {
      console.log("prev");
      if (currentStep == 2) {
        if (this.$attrs.has_profile) {
          this.$nextTick(() => {
            const tour = this.$tours["myTour"];
            tour.currentStep = currentStep - 2;
          });
        }
      }
```

My steps are changed whether the user has profile.
