### ISSUE TITLE
steps of vue-tour is empty

### ISSUE THREAD

**Issue by owlran** [pulsardev/vue-tour#187]
**Describe the bug**
steps are initialized in the mounted stage, then call the `start()` 
TypeError will be thrown -> `Cannot read property 'before' of undefined`

**To Reproduce**
open the following link.
https://codesandbox.io/s/brave-dubinsky-lzkb2?file=/src/App.vue

**Expected behavior**
vue-tour's prop `steps` should be updated correctly.

**Additional context**
It looks like prop steps was not updated immediately.
But if i await a tick to call `start()`, prop steps will be ok.

**Comment by HZooly** [comment]
I don't get the error `Cannot read property 'before' of undefined`, are you able to reproduce again?

**Comment by owlran** [comment]
no.. It seems to be working fine

**Comment by owlran** [comment]
hi @HZooly,

I updated the code in above codesandbox link.

this error can be reproduced, if steps is assigned a array of steps.

```js
this.steps = [
      {
        target: "#v-step-0", // We're using document.querySelector() under the hood
        header: {
          title: "Get Started",
        },
        content: `Discover <strong>Vue Tour</strong>!`,
      },
      {
        target: ".v-step-1",
        content: "An awesome plugin made with Vue.js!",
      },
      {
        target: '[data-v-step="2"]',
        content:
          "Try it, you'll love it!<br>You can put HTML in the steps and completely customize the DOM to suit your needs.",
        params: {
          placement: "top", // Any valid Popper.js placement. See https://popper.js.org/popper-documentation.html#Popper.placements
        },
      },
    ];
```
