### ISSUE TITLE
Is there any way to disable next/previous button?

### ISSUE THREAD

**Issue by humayunkabir** [pulsardev/vue-tour#188]
I have a tour for a form and it continues after submitting the form. The form is in the modal. So If the modal is open, it shouldn't go forward.  I need to disable the **next** button for this reason. After submission of the form, It should be enabled again. I couldn't find any way to do it. Need help.

Thanks.

**Comment by HZooly** [comment]
You have to customize the template with your own conditions: https://github.com/pulsardev/vue-tour/wiki/Customizing-the-Template
