### ISSUE TITLE
Can i use vue-tour 2 ways? 1 as intended and another as a tooltip?

### ISSUE THREAD

**Issue by ricky11** [pulsardev/vue-tour#196]
I was going to install another vue tooltip library which is also based on popper.js but then i thought why cant i use vue-tour as a tooltip?

1) Can I have only 1 step? 

2) Can I show steps on mouseover ?

**Comment by ricky11** [comment]
any suggestions on this? i actually manage to use it as a tool tip as well but seems hacky.

**Comment by HZooly** [comment]
1. Of course you can setup Vue Tour with a single step.
2. You can start the tour whenever you want, it can be a mouseover event.

You could imagine start tour on mouseover and stop tour on mouseleave.

**Comment by ricky11** [comment]
thanks for your quick answer.  im trying to load vue-tour only when needed, instead of in my main.js file do you have a suggestion to load the following code lazily? not sure how to do it for a module, but I know how for a component.

import VueTour from 'vue-tour'
require('vue-tour/dist/vue-tour.css')
Vue.use(VueTour)
