### ISSUE TITLE
How do you go directly to step 2 or step 3 ?

### ISSUE THREAD

**Issue by ricky11** [pulsardev/vue-tour#198]
I could not find much information on the methods attached to     this.$tours.xx

all I could find was .start (in the docs) and .finish() which was in the github issues.

1) are there any others I can use?
2) Are there any methods I can use to go directly to step n ?

Thanks
Rish

**Comment by ricky11** [comment]
got it.. this.$tours['qsError'].start(n)

was this anywhere in the docs that I missed? if it was was a bit hard to find :)

**Comment by HZooly** [comment]
You are right, the feature to start at a specific step is not mentioned in the doc/wiki. We have to rework that one.
Thank you for sharing this!

**Comment by ricky11** [comment]
Thank you for updating the docs.
