### ISSUE TITLE
Custom Button Text / i18n support

### ISSUE THREAD

**Issue by MaximilianFranke** [pulsardev/vue-tour#2]
Hello guys,
it would be nice to have the static texts like 
Skip tour
Previous
Next
Finish
configuratable. That would be nice for tours on non english pages ;)

**Comment by mmorainville** [comment]
Hi @MaximilianFranke,

We plan to make this simplier but actually you can already do this.
Someone asked the same things in an other issue. You can take a look at it here:
https://github.com/pulsardev/vue-tour/issues/1

Hope it helps!

**Comment by MaximilianFranke** [comment]
Ups i didnt look at the clodes issues! Thank you ;)
