### ISSUE TITLE
Keyboard events firing all tours custom callbacks

### ISSUE THREAD

**Issue by zanedev** [pulsardev/vue-tour#20]
The keyboard events are registered globally so if you have multiple tours in your app, it will fire the custom events for every tour.  I ran into this with the stop callback, I was running some custom logic specific to each tour on the stop callback and it was running every single tour's stop logic when I hit the escape key instead of the running tour's stop callback.

I worked around it for now by checking that the current tour is running first in the callback:
`if (this.$tours[this.tourName].isRunning)....`

Possible fix: namespace the events or only register/unload them when a tour is in progress rather than on mount?

**Comment by Outpox** [comment]
Hi there,
This was something we didn't think about, and I do like the idea to fire the events when a tour is in progress rather than no check at all. 
@mmorainville your input would be interesting :)

**Comment by mmorainville** [comment]
Indeed, it's a great idea! Thanks @zanedev for the input.
However we have to think of every use case, wouldn't be a problem if one day we want to make a hook available when the tour is not started yet or when the tour is finished?
For example beforeStart and afterEnd callbacks?

Otherwise the namespace would also be a good idea, we should take a closer look and make some tests.

**Comment by buksy90** [comment]
Hi there, its been two years since the bug has been reported and it is still present :) .

I think it would be enough to move window.addEventListener('keyup', this.handleKeyup) from mounted() to start()

**Comment by mmorainville** [comment]
Hi @buksy90,

Indeed we are at the same too cautious to add features without thorough thinking (to avoid regressions or breaking changes) and too busy on other projects to keep track of old issues like this one.

But in this case as you said, it should be enough to move the listener in the start() method (and thus to remove the listener in the stop method). Unless two tours run at the same time... which is not really not recommended but possible and maybe some people do that? But in this case the behavior should be the same as now, so it's not really breaking anyway...

Then, a PR would be welcome on this one, it's a good first issue to start contributing. :)
