### ISSUE TITLE
Using ESC key doesn't call onEnd/onSkip callbacks

### ISSUE THREAD

**Issue by m-mohr** [pulsardev/vue-tour#202]
**Describe the bug**

While the buttons call the onEnd/onSkip callbacks just fine, no callback is used when the ESC key is used.

**To Reproduce**
1. Specify onEnd and onSkip callbacks
2. Press ESC key

**Expected behavior**
I'd expect that one of the callbacks is fired to inform me that the tour has ended.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 92.0.4515.107
 - Version Vue-Tour 2.0.0

**Comment by nyfer** [comment]
@mmorainville  Is this already being worked on or can i take this up?

**Comment by mmorainville** [comment]
Hi @m-mohr, @nyfer,

This is not being worked on at the moment, but I wonder if it's really a bug actually.
The end callback is actually called onStop and is already called when pressing the ESC key.

That can be seen in the VTour component:
```
    stop () {
      this.customCallbacks.onStop()
      document.body.classList.remove('v-tour--active')
      this.currentStep = -1
    },
    ...
    handleKeyup (e) {
      ...
      switch (e.keyCode) {
        ...
        case KEYS.ESCAPE:
          this.isKeyEnabled('escape') && this.stop()
          break
      }
    },
```

And pressing ESC key really stops the tour, it doesn't skip it, so I don't think it's conceptually correct to make it trigger the onSkip callback.

I added the onStop callback in the documentation, it was indeed not documented though, sorry for that.
https://github.com/pulsardev/vue-tour/wiki/Callbacks

**Comment by m-mohr** [comment]
Thanks for your thoughts. ESC ends or skips the tour (not sure), so I'd expect to either have an onEnd or onSkip event fired (or a new onEsc). Not sure which fits better, but one of them should be fired. I need to react on when the tour "disappears" and ESC right now results in a "bug" on my side. It was not the case that onEnd was called when I opened the issue, would need to check again.

**Comment by m-mohr** [comment]
Ah, now I see that there's a new "onStop" in the docs now, wasn't aware of that. I was confusing it with "onFinish", which I used before. Alright that works for me, thanks!
