### ISSUE TITLE
onFinish call back doesnt seem to fire when invoked

### ISSUE THREAD

**Issue by nyfer** [pulsardev/vue-tour#209]
Have tried the below code to call the finish method, but it doesn't. Works for onskip. Am i missing something?
myCallbacks: {
onSkip: skipTour,
onFinish: finishTour
}

**Comment by mmorainville** [comment]
Hi @nyfer,

No it should work. Have you defined the finishTour function in the exact same way you defined skipTour?
If yes, can we have more details, or maybe a CodePen reproducing the issue?

**Comment by nyfer** [comment]
I did use the same function ie finishTour for onSkip and it worked, but same doesnt work for onFinish

**Comment by nyfer** [comment]
I had missed this `:finish="tour.finish"`  and i think its not there in documentation as well. 
 I checked the source code and added it the custom template
After that it started working.
