### ISSUE TITLE
Contour blurring [BUG]

### ISSUE THREAD

**Issue by tol64** [pulsardev/vue-tour#214]
To avoid contour blurring in some cases, round up the value shown below (.v-step) to a whole number (-659.438px > -659px).

```
element.style {
    position: absolute;
    inset: auto auto 0px 0px;
    margin: 0px;
    transform: translate(763px, **-659.438px**);
}
```

**Comment by mmorainville** [comment]
Hi @tol64,

We use Popper.js under the hood for the tooltip positionning.
It seems the issue is on their side and an option is available to fix this: https://github.com/floating-ui/floating-ui/issues/682.
You can pass Popper options as step params directly.
