### ISSUE TITLE
When i clikc on Esc the function this.callbackTour.onStop is called ..

### ISSUE THREAD

**Issue by joffreyBerrier** [pulsardev/vue-tour#22]
In my example, i have lot of IView selects, when i want to quit this select i click on esc but this function : callbackTour.onStop is called..

i have a condition on this function, when the client click on stop vue tour, i have a message who indicated to the client where he had to relaunch the tour.

so this message appear when the client click on esc.. it's weird

Do you have an idea ?

**Comment by mmorainville** [comment]
Hi @joffreyBerrier,

It seems related to this issue: https://github.com/pulsardev/vue-tour/issues/20
As the callbacks are registered globally and not namespaced, if they are activated they can indeed be triggered from anywhere in the app.

We'll track this problem in the other issue.
