### ISSUE TITLE
Can't translate button labels and tour texts at all

### ISSUE THREAD

**Issue by kaszarobert** [pulsardev/vue-tour#229]
**Describe the bug**
For a non-English site I need to translate everything into multiple languages. There's no documentation about that. I tried advises in multiple issues but none of them worked.
https://github.com/pulsardev/vue-tour/issues/1 
https://github.com/pulsardev/vue-tour/issues/2 
https://github.com/pulsardev/vue-tour/issues/53

1 simple question: is it possible to translate something at all? Or am I wasting my time with this library if I'm not interested in an English UI?

**Comment by mmorainville** [comment]
Hi @kaszarobert,

It's totally possible to translate the labels of the buttons. The answer is in all three issues you've listed.
You just have to use the `labels` prop of the `v-step` component.

```
          <v-step
            v-if="tour.currentStep === index"
            v-for="(step, index) of tour.steps"
            :key="index"
            :step="step"
            :previous-step="tour.previousStep"
            :next-step="tour.nextStep"
            :stop="tour.stop"
            :is-first="tour.isFirst"
            :is-last="tour.isLast"
            :labels="tour.labels"
          >
```

```
labels: {
  buttonSkip: 'Skip tour',
  buttonPrevious: 'Previous',
  buttonNext: 'Next',
  buttonStop: 'Finish'
}
```
