### ISSUE TITLE
Transparent Visualization making problem

### ISSUE THREAD

**Issue by mahamudul87** [pulsardev/vue-tour#25]
when tour toast showing on another field like text field or date field then vue tour previous or next button is not working due to transparent toast.

**Comment by mmorainville** [comment]
Hi @mahamudul87,

I'm not sure what you mean... Could you update a screenshot please?
It seems like a z-index problem but then you should have no problem customizing the CSS for your needs.

**Comment by Outpox** [comment]
Closing this as we had no answer, feel free to re-open this issue if you still need help!
