### ISSUE TITLE
Disable interaction with any elements while tour is displayed

### ISSUE THREAD

**Issue by max-tet** [pulsardev/vue-tour#254]
While a tour step is active, it is possible to click on the hightlighted elements. (The other ones seem to be covered by the shadow and are not clickable? Not sure if I got that right.)

This allows users to click an element and e.g. open a modal that interacts with the tour step in weird ways.

Is it possible to disable any interaction with anything on the page except the tour buttons?

**Comment by yax7** [comment]
Hey,

edit: you just can deactivate the pointer events.

```
.v-tour__target--highlighted {
  pointer-events: none !important;
}
```

**Comment by max-tet** [comment]
That worked great, thanks!

**Comment by DSoftwareArtist** [comment]
Dont' worked.
