### ISSUE TITLE
Install with Nuxt3

### ISSUE THREAD

**Issue by SamG92** [pulsardev/vue-tour#257]
Hi there,

Did you manage to install vue-tour with Nuxt3 ? I would be very interested to know how.

Thanks a lot
Samuel

**Comment by HZooly** [comment]
@SamG92 unfortunately the lib is not compatible with Nuxt 3 at the moment.

**Comment by alvintheodora** [comment]
HI @HZooly , may I know any updates on nuxt 3? 
I tried to define plugin `vue-tour.client.ts` and I got error `Cannot set properties of undefined (setting '$tours')` when I define plugin like following:
```
import VueTour from "vue-tour";
import type { Plugin } from "vue";

import "vue-tour/dist/vue-tour.css";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueTour as unknown as Plugin);
});
```
Thanks
