### ISSUE TITLE
Embed Image in tour

### ISSUE THREAD

**Issue by hyejunan** [pulsardev/vue-tour#258]
Hi there,

Is it possible to embed image in the tour step?
I tried to use html img tag but it seemed like not working.

Thank you,
Hyejun

**Comment by MuhammadTalib** [comment]
You can simply customize you vue-tour steps by adding the following lines to your html template of the component.
please check the following gist https://gist.github.com/MuhammadTalib/b8ff43f307024df408a857d3fbe71fa3

or you can follow this link https://github.com/pulsardev/vue-tour/wiki/Customizing-the-Template to get how to customize your steps
