### ISSUE TITLE
Tooltip on mobile covers element which it should point at

### ISSUE THREAD

**Issue by epsiloneridani** [pulsardev/vue-tour#26]
Screen size 320px. 

![image](https://user-images.githubusercontent.com/10383892/41088303-777408e6-6a3f-11e8-901e-bbb7002ed841.png)

**Comment by mmorainville** [comment]
Hi @epsiloneridani,

It doesn't to be a problem with vue-tour but rather with Popper.js, the library we use to help us position the tooltips in extreme conditions like this one so you may want to look at their documentation.

Also you could try to use a different default orientation for your tooltip, like `top` or `bottom`.
