### ISSUE TITLE
Cannot access parent component element

### ISSUE THREAD

**Issue by martiendt** [pulsardev/vue-tour#28]
Hi, it's working on my pages component, but how can i call parent component element like header or sidebar ? i tried to call parent element id but that step it's not working.

**Comment by mmorainville** [comment]
Hi @martiendt,

I'm not sure I understand your problem very well. Could you be more precise please? What are you trying to achieve exactly?

**Comment by Outpox** [comment]
Closing this issue as we had no answer in while. Feel free to re-open the issue if you still need help!
