### ISSUE TITLE
Next step not showing

### ISSUE THREAD

**Issue by Jomari-Macaraig** [pulsardev/vue-tour#29]
Hi,

I'm experiencing some problems regarding having the next step of my tour working. The second step of my tour isn't appearing wherein its target element is hidden via `v-show` statement.

**Comment by mmorainville** [comment]
Hi @Jomari-Macaraig,

It should work with a v-show as the element is in the DOM and should be targetable.
Could you reproduce the problem in a CodePen please?

Regards,
Mathieu

**Comment by Outpox** [comment]
Any update on this one @Jomari-Macaraig ? Have you been able to fix your issue?
