### ISSUE TITLE
onUpdate callback

### ISSUE THREAD

**Issue by eyaylagul** [pulsardev/vue-tour#30]
Hello, thank you too for wrapper but i have a problem.
`
data(){
 return {
anyData: false,
steps: [
		{
		target: '.registration',
		content: 'Discover <strong>Vue Tour</strong>!',
		params: {
				onUpdate(data) {
					this.anyData = true;
				}
			}
		},
	]
     }
}
`

if i trying change data status to anyData, anyData is not changing.
or if i call method  there, returning error " the methodName() is not function."

How can i vue method, props or data in that like event?

**Comment by mmorainville** [comment]
Hi @eyaylagul,

It seems to be a typical problem concerning the scope of `this`. You should put `this.anyData = true` in a normal method in the `methods` property of your Vue component and call it afterwards like this:

```js
myCallbacks: {
  onPreviousStep: this.myCustomPreviousStepCallback,
  onNextStep: this.myCustomNextStepCallback
}
```

You can find more details on callbacks and things like that in the documentation: https://pulsar.gitbooks.io/vue-tour/callbacks.html

**Comment by eyaylagul** [comment]
Thank you for reply, but i need use onUpdate or onCreate event which provided Popper.js. I reviewed your code maybe i missed any line releated my problem. so i asked. The callbacks it is not enough for me. Have a good day :)
