### ISSUE TITLE
Option for "no target element"

### ISSUE THREAD

**Issue by jvenema** [pulsardev/vue-tour#31]
It would be great to have an option that just does a center-screen pop-up by specifying no target element. This would allow for, for example, an introduction or closing statement.

**Comment by mmorainville** [comment]
Hi @jvenema,

It's an interesting idea indeed. A PR would be welcome! :)

**Comment by mattgreenfield** [comment]
I was after this too and used @sheehan's solution to target 'body' but it does feel like a hack.

I would imagine this being an alternative to providing a `target` option and I can see a need to position it in different places around the screen.

```
{
  target: false,
  content: 'This is a centered pop-up.',
  params: {
    placement: 'center', // or 'bottom', 'bottom-left', 'top' etc etc
  },
}
```

I see there's a PR for similar functionality here https://github.com/pulsardev/vue-tour/pull/51/files

**Comment by mmorainville** [comment]
PR has been merged: https://github.com/pulsardev/vue-tour/pull/51/files.
But as of now the feature stay limited to the step being placed in the viewport's center.
We'll see to improve that for the Vue 3 version of vue-tour but the Vue 2 version will likely stay like this (you can always manually tweak the CSS on v-step--sticky to place it wherever you want though).
