### ISSUE TITLE
Async inclusion/import

### ISSUE THREAD

**Issue by andreasvirkus** [pulsardev/vue-tour#42]
Hi,

First off - great component! :)

Is there a way to not use the `Vue.use()` pattern and to load in the component on-demand?
Even though the component is 10kB gzipped (according to Bundlephobia), that's still 10kB
that _every_ reoccurring user would need to download and 30kB for the browser to parse.

Cheers,
Andreas

**Comment by mmorainville** [comment]
Hi @andreasvirkus,

I'm afraid that the `Vue.use()` is mandatory to benefit of the global `this.$tours` property and to load the `v-tour` and `v-step` components automatically.

However, you don't have to necessarily put `Vue.use()` in your Webpack entry point (usually `main.js`).
So you could import it in an entirely different js file, say `shared/vue-tour.js` which would contain the `Vue.use()` call and then import this component only where you need it.

I haven't tested this solution and it depends on your Webpack config of course, but it should work.

**Comment by andreasvirkus** [comment]
Thanks for getting back to me so soon!

What I'm currently attempting is to have `vue-tour` in a wrapper component, which also includes registration within itself.

I'm also having trouble figuring out how to define my steps array if (almost) every step would be under a different route?

If you wouldn't mind having a look at my setup:
`App.vue`
```
    ..
    <q-tour v-if="giveTour"/>
  </div>
</template>

<script>
export default {
  components: {
    QTour: () => import('@/components/QTour')
  },
  data () {
    return {
      // A flag for when to load in the component that wraps vue-tour
      giveTour: false
    }
  }
}
</script>
```
`QTour.vue`
```
<template>
  <v-tour name="app-setup"
    :steps="steps"
    :callbacks="callbacks"/>
</template>

<script>
import Vue from 'vue'
import VueTour from 'vue-tour'

Vue.use(VueTour)

export default {
  name: 'q-tour',
  data () {
    return {
      steps: [
        // Not sure how to mark these down if the steps will be scattered over different routes
        // Will the lookup happen after the route so I can just scatter different data-attributes
        // under different views?
      ],
      callbacks: {
        onNextStep (currentStep) {
          // Let's say I have a step index mapping with matching route names
          this.$router.push({ name: mapping[currentStep] })
        }
      }
    }
  },
  created () {
    this.$tours['app-setup'].start()
  }
}
</script>
```

Calling `.start()` gives me the following error:
```
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'start' of undefined"
```

**Comment by glorat** [comment]
I followed what @andreasvirkus did except I call `start` inside the `mounted` callback rather than `start`. It seems to work for me and webpack also now pulls the code outside of my entry point bundle, helping  load speed

**Comment by mmorainville** [comment]
It's now documented here at the end of the page: https://github.com/pulsardev/vue-tour/wiki/Getting-Started.
