### ISSUE TITLE
Support querySelectorAll

### ISSUE THREAD

**Issue by timpulver** [pulsardev/vue-tour#43]
Would be great if there was a way to use `querySelectorAll`, e.g. to select the second span via:

```
span:nth-child(2)
```

Maybe something like this:

```
target: 'span:nth-child(2)',
content: `This is the second span`,
params: {
  selectionMethod: 'querySelectorAll',
},
```

If the result of the selection is an array, it could just use the first element.

**Comment by Outpox** [comment]
Hey there!  
Internally the target you provide for your steps is already retrieved using `querySelector` as you can see in [`VStep.vue` L.73](https://github.com/pulsardev/vue-tour/blob/master/src/components/VStep.vue#L73):   
```
let targetElement = document.querySelector(this.step.target)
```

I've tested the following target on the demo: `#v-step-1 h2:nth-child(1)` and it's working as expected.

**Comment by mmorainville** [comment]
Indeed to support what @Outpox said I've made a quick screen capture:
![201809181713](https://user-images.githubusercontent.com/1155743/45697627-7e9bd400-bb66-11e8-99c2-da93370ce82c.gif)
