### ISSUE TITLE
Hack-ish way to add highlight to active element

### ISSUE THREAD

**Issue by Art3miX** [pulsardev/vue-tour#48]
I know this feature is something you guys are/will work on, but I can't wait so i found an easy hack that works for me and I think it might help others as well so i'm sharing this here.
More about this feature in here: #11 

## Code
You can find the full code here:
https://gist.github.com/Art3miX/88fc3a56353ca8045f49bc8f7cc6543f

I use it as a mixin because i do several tours (1 per specific route), so its an easy way for me to add it quickly, but you can simply take the code from the functions and add it to the place you need it. 
The css is in a comment at the end of the page.

## Support
The code use CSS pointer-events and JS classList add and remove functions, you can find the support table here:
https://caniuse.com/#feat=pointer-events
https://caniuse.com/#feat=classlist

Only tested on chrome for now, but should work for all major versions.

### Highlight
It basically adds a shadow around the active step element with 0.6 opacity which gives a nice background above the rest of the page. 
### Disable clicks
It uses pointer-events: none on the body to disable all click events, and the active step element uses pointer-events: auto, to enables clicks only on that active element.
You can disable events for all of the page including the active element if wanted, simply remove the class from the rule, BUT don't forget to leave pointer-events: auto; on the v-tour class so the tour will be clickable.
### Responsive
I added few media queries to make the shadow smaller for smaller devices simply because we don't need 10kpx around the div for devices that are 700px wide.
The size of the shadow is still larger from the size of the screen just in case, this can be modified to be smaller if you want to.

## Notes
I built it for my self and it has everything I need, i will most likely upgrade it a bit for my needs and will keep the file updated, but this is a simple hack-ish way to get it done, make sure to test it before using it. 

I'm not working on this project in any way, this is simply how i implemented this feature for my own use, so take the code and play with it for your use, i know the guys are working on this feature in a more stable and better way.

### Suggestions / bugs
Any suggestions to make it better will be appreciated, and if you found a bug let me know please.

**Comment by mmorainville** [comment]
Wow thanks a lot for your work @Art3miX!
We'll definitely take a deeper look at it. The idea of using a drop-shadow on the item is really clever and I must say that we didn't think of it initially. It would prevent the need to listen to window resize events which is great!

You are free to make a PR if you want, so that you'll appear in the contributors to the project, but we'll indeed review the code and make it a global (or maybe a step ?) option rather than a mixin.

**Comment by Art3miX** [comment]
Sure i might look into it in the weekend, i never did a PR for public projects (only for private) so any guides on what would be the best way? 

Fork, add the code, and send a PR?

**Comment by mmorainville** [comment]
Yes that's pretty much it! :)
The only "picky" things is that you commit message should respect the Git Commit Guidelines written in our [CONTRIBUTING.md](https://github.com/pulsardev/vue-tour/blob/master/CONTRIBUTING.md#git-commit-guidelines).

It's very important to allow us later to automatically generate a nice and correct changelog afterwards.

So here for example you could make only one commit that would be something like:
feat(highlight): add the possibility to highlight elements during the tour
Or something like that. ;)

**Comment by trafium** [comment]
Thank you for great and quick hacklution! With minimal tweaks it worked pretty well for me. Although in my case I had to make each shadow 10 times larger, since vertical scroll makes it possible to scroll out of shadowed area. 
I wonder if there are possible performance caveats with > 20,000 shadow spread.

**Comment by Art3miX** [comment]
@trafium I know there is a limit each browser sets to the maximum shadow size some where in the 64k, but if you will try to do an animation to the box-shadow property i'm sure you will see some performance issues, so i guess for mobiles or smaller devices it is not advised to have large shadow size this is why i added the media queries (nothing tested, so make sure to test it for your case).

About the scroll issue, usually the tour (step) is focused on a small part of the document, and usually it fits the screen, or a lot less than 20k pixels (don't forget the box-shadow sets 20k pixels on each side so that's 80k in total!), so usually you don't need to scroll when the tour is active or you need to scroll just enough to see the targeted element and the step window, i would suggest to disable the scroll of your document or so the user will be able to scroll just enough to see the targeted element and the tour window for cases where the targeted element is bigger than the viewport.

Disabling the scroll is good for the tour because you want the user to stay focused on the highlighted element and not wonder around the page, also this solves the too big box-shadow issue you can set it to be a lot less.

**Comment by Art3miX** [comment]
After thinking about the issue above (where the box-shadow doesn't cover the whole document) i figured out the best way would be to limit/disable the scrolling of the document to the target element only, so if the element fits the viewport you disable scrolling (it fits, no need to scroll) if its bigger than the viewport you need to allow scrolling only enough to see the targeted element and the step window, but i couldn't make it work because we need to know the height of the element and also the position in the document, but those both values can change any time and its hard to make it work for all 100% cases.

What i did for my use-case, I added a small box-shadow with 50px width and 50px blur to the :after pseudo element, this allows me to highlight the element just enough to make sure its visible, and because i disable the events for the rest of the page, the users still can't click on the rest of the document without continuing the tour.

![image](https://user-images.githubusercontent.com/40179351/47555409-7298f400-d914-11e8-9c06-d8120a221e75.png)


I find that its the best easy way to add that highlight effect to any use-case there is, while the look of it is not the best, this can be easily changed.

**Comment by mmorainville** [comment]
Hi @Art3miX,

Thanks for your contribution and the explanation. It's indeed a good compromise as it still fulfil its job of highlighting the targeted component.
So it's ok for me and if someone want to customize it, he would just have to override the CSS of the shadow so it's fine by me.
We still haven't been able to review your PR but we should have time to do that soon!

**Comment by Art3miX** [comment]
Hi @mmorainville,

I have create a new PR because the old one had a lot of stuff that was not related to the feature, the new PR contains the new style of the highlight.

**Comment by mmorainville** [comment]
Hi @Art3miX,

It has taken a looot of time but we finally have merged it! We had been busy on some other projects and in the meantime we wanted to improve the delivery process of vue-tour so that in the feature we could accept and merge PRs more easily.

We have migrated the project to Vue CLI 4 and put the landing page out of the master branch (while still using it for the e2e tests on the CI).

Anyway, thank you very much for your work on this feature! The documentation is here: https://github.com/pulsardev/vue-tour/wiki/Features.

And again, sorry for the delay...

Kind regards,
@mmorainville

**Comment by jonalxh** [comment]
Hi. Is there a working example of highlight? I've tried with highlight option and only puts a border to the step element, but background keeps in same color, not blurred nor opaque.
