### ISSUE TITLE
Popper options

### ISSUE THREAD

**Issue by zanedev** [pulsardev/vue-tour#5]
Would be nice if we could specify all the popper.js options if needed.  Why not just ferry them along to popper if they are defined?  Currently it appears to only allow specifying the `placement` option.

**Comment by mmorainville** [comment]
Hi @zanedev,

Indeed! It would be useful and not hard to do, we'll try to push it in the v1.0.0 coming soon (before the end of the week normally) or if you want you can make a PR, it would be a good first issue for contributing!

**Comment by Outpox** [comment]
I'm on it :D

**Comment by Outpox** [comment]
It's available in the [feature/custom-callback-management](https://github.com/pulsardev/vue-tour/tree/feature/custom-callback-management) if you want to try early. It should be merged in master tomorrow and released this week-end.

**Comment by zanedev** [comment]
Thanks @Outpox!  This will make vue tour much more flexible.  I'm going to test it out today and I'll report back.

**Comment by zanedev** [comment]
Just wanted to confirm that this branch with the added options feature is working as expected.

Curious how long to get an official release even if beta?  Need to include this in our upcoming release and would rather not hard code a branch etc.

**Comment by mmorainville** [comment]
We plan to deliver tomorrow evening around 19:00 CET. So at the latest you should have it on Saturday ;)

**Comment by mmorainville** [comment]
Hi @zanedev,

The feature is ready!
