### ISSUE TITLE
Adding tour steps across components

### ISSUE THREAD

**Issue by willishq** [pulsardev/vue-tour#52]
I want to create tours based on what components are on a page, potentially through many layers of nesting. Is it possible to add steps across multiple components, or to add a step to an actual component?

If I were to add child steps would I need to (for instance) return them through a callback on my component and merge them into a computed “steps” property?

What would be the best way to achieve this?

**Comment by Art3miX** [comment]
From the look at the source code, the step is searching for the target in the actual DOM, so when you set a target, if the target is in the DOM the step will work, so all components that are nested inside the parent component with the tour will work.

If you want to have tours on different components (not nested inside the parent with the tour), currently you can simply create multiple tours and start them when the component is mounted.
