### ISSUE TITLE
[Question] How can I show a step content after user performs an action(like open a dropdown menu)

### ISSUE THREAD

**Issue by kanteankit** [pulsardev/vue-tour#59]
**Use Case:**
While user goes through each step, at some point I want the user to open a dropdown menu. After user opens the dropdown menu, the tutorial will explain the menu options.

**Sandbox link:** https://codesandbox.io/s/4jpnjqw8z9

**Issue:**
Using the `onNextStep` callback, I am able to open the dropdown menu using javascript. But, since, the menu was not open when the page loaded, `vue-tour` does not show the step 3 popper.
How can I force `vue-tour` to show the next step content after the dropdown menu is opened?

**Comment by SohrabZ** [comment]
@kanteankit Here is the hack that I've used to open the dropdown menu and fix the position of Popper (tooltip or tour step 😄):
```js
if (currentStep === 1) {
    setTimeout(() => {
        this.$refs.mainMenu.click()
        setTimeout(() => {
            $(window).scrollTop($(window).scrollTop() + 1)
        }, 100)
    }, 10)
}
```

**Comment by mmorainville** [comment]
Hi,

SohrabZ's solution should work, even if it feels hacky, but now you may be able to solve your issue (if not already solved... ^^') with the `before` hook which handles Promises: https://github.com/pulsardev/vue-tour#before-ui-step-functions.
