### ISSUE TITLE
Support for title slot in options

### ISSUE THREAD

**Issue by zanedev** [pulsardev/vue-tour#6]
Feature request: It's really common to have a title in addition to content.  Maybe provide a slot for title also and allow passing in as options?

I'm getting around this for now by changing step.content to an object and doing the following but concerned it might break in future if not a baked in option.

```
<span v-if="step.content.title" v-html="step.content.title"></span>
<span v-if="step.content.text" v-html="step.content.text"></span>
```

(btw i'm under release crunch so I can't contribute at the moment but certainly can in the future)

**Comment by mmorainville** [comment]
Hi @zanedev,

It would indeed be useful! I'll tackle this one maybe with something like this:

```
    <slot name="header">
      <div class="v-step__header">
        <span v-if="step.header.title" v-html="step.header.title"></span>
        <div v-if="step.header.rightBlock" v-html="step.header.rightBlock"><!-- Code for a close button by default? --></span>
      </div>
    </slot>
```

I'll see, but for now indeed the solution was to just customize the step.content with custom HTML.

**Comment by mmorainville** [comment]
Hi @zanedev,

You can check the feature on the custom-callback-management branch.
https://github.com/pulsardev/vue-tour/commit/8cd3883bafef6ca9b32d5ad231c44522097d3dfb

**Comment by zanedev** [comment]
@mmorainville branch looks good to me 👍  Yeah if you have time maybe adding an optional close `X` with another param would make sense.  Looking forward to the next release!

**Comment by mmorainville** [comment]
Hi @zanedev ,

The feature is ready, the documentation should come soon!
Yes an optional close button would be great, but it requires some thinking to do it right. For example should we allow the user to pass a custom function for the close button or can he customize the button through the step options, etc.

We'll do it later if it's really needed.

**Comment by DerekNMartin** [comment]
@mmorainville For what it's worth, I would love an option for a close X button in the top right corner. I think it's an important feature.
