### ISSUE TITLE
Skip Tour button persistence

### ISSUE THREAD

**Issue by threeel** [pulsardev/vue-tour#60]
hello and thank you for this nice component. Is there a possibility to make the hook on the skip tour and persist it in the localstorage so the next time it remembers the user preference.
maybe there is another way.
if you can point to the right direction would be great.

**Comment by mattgreenfield** [comment]
You can add a custom callback on the `onStop` event. See the docs here https://pulsar.gitbooks.io/vue-tour/callbacks.html
