### ISSUE TITLE
Get steps data from target step element dataset

### ISSUE THREAD

**Issue by bm-stschneider** [pulsardev/vue-tour#62]
I save the step information in the dataset of the target of the step and want it to be read when the step is active. How is this possible with vue-tour? Can I get the step target easy?

**Comment by mmorainville** [comment]
Hi @bm-stschneider,

You normally have access to all the VTour and VStep properties thanks to the global `$tours` property.
So you should be able to do this to get the target (I didn't test this but it should work):
```js
this.$tours['myTour'].steps[currentStep].targetElement
```

**Comment by bm-stschneider** [comment]
thank you for answering before the 2. birthday of this question :)

**Comment by mmorainville** [comment]
Yes sorry about that... `vue-tour` is supported on our free time and we also have to update and work on other side projects so it's not always easy to find the time to answer every issues, even simple ones.
I guess you found out the answer by yourself during the time, but I prefer to answer for people who would have the same problem.
