### ISSUE TITLE
Provide own labels

### ISSUE THREAD

**Issue by bm-stschneider** [pulsardev/vue-tour#63]
How can I in general provide custom labels for the general labels of next prev etc. ?

**Comment by mmorainville** [comment]
Hi @bm-stschneider,

You can customize the labels by two different ways: using the new `labels` option property (https://pulsar.gitbooks.io/vue-tour/content/tour-configuration.html) or by customizing the template (https://pulsar.gitbooks.io/vue-tour/content/customizing-the-template.html).

The first solution is simple and straghtforward, the second one is more complex and cumbersome but allow you to have a lot more control over what you want to display.
In your case I guess the first option should work just fine.
