### ISSUE TITLE
Difference between skip and stop callback

### ISSUE THREAD

**Issue by alexandreDavid** [pulsardev/vue-tour#64]
Hi, it would be great to find a way to know if the user clicked on "Finish" or on "Skip".
Proposal:
- if click on skip: Call a method skip() with a custom callback onSkip and call after stop()

- if click on finish: Call a method finish() with a custom callback onFinish and call after stop()

**Comment by alexandreDavid** [comment]
If okay, I can send a PR

**Comment by mmorainville** [comment]
Indeed it would be a good idea! Even if right now one way to know that is to check in the callback if the step is the last one or not.

**Comment by mmorainville** [comment]
Hi @alexandreDavid,

It took a while but your PR has been merged in v1.3.0! Thanks for your contribution!
