### ISSUE TITLE
E2E not working in demo

### ISSUE THREAD

**Issue by HZooly** [pulsardev/vue-tour#65]
Cypress `before` fails `CypressError: cy.visit() must be called with a string as its 1st argument`.

`Cypress.env('VUE_DEV_SERVER_URL')` is `undefined`.

Perhaps you missed to commit your env files ?

**Comment by mmorainville** [comment]
Hi @HZooly,

We migrated vue-tour to Vue CLI 4 and migrated the landing page used for the e2e tests out of the master branch. In the process we no longer use the env variable VUE_DEV_SERVER_URL so this issue should be resolved.
