### ISSUE TITLE
Multi page tours

### ISSUE THREAD

**Issue by memic84** [pulsardev/vue-tour#66]
What is the best way to handle multi page tours, where one of the next steps should go to another vue route. The problem i have is timing.. i already searched the issues but could find anything that would solve my problem.

**Comment by patric-eberle** [comment]
@memic84 I'm also new to this plugin. But can't you define a [custom template](https://pulsar.gitbooks.io/vue-tour/customizing-the-template.html) for the prev/next buttons and then use the [callbacks](https://pulsar.gitbooks.io/vue-tour/callbacks.html) or a custom action to redirect to the next page?

**Comment by lino** [comment]
Please have a look at #12
