### ISSUE TITLE
v-for/v-if bad practice (custom template)

### ISSUE THREAD

**Issue by wilmouths** [pulsardev/vue-tour#70]
The v-if/v-for is not useful and we can avoid the v-for in the template customization, the following lines:
```
v-if="tour.currentStep === index"
v-for="(step, index) of tour.steps"
:key="index"
:step="step"
```

can be replaced by : 
```
v-if="tour.steps[tour.currentStep]"
:step="tour.steps[tour.currentStep]"
:key="tour.currentStep"
```

**Comment by wilmouths** [comment]
Erratum : The bubble does not change location, it remains fixed but the step changes well

**Comment by JackEdwardLyons** [comment]
Any news on this?

**Comment by wilmouths** [comment]
> Any news on this?

[It was updated last month (Dec. 2019)](https://github.com/pulsardev/vue-tour/commit/e6a2a2d4da7d146340e22e750efb811a214b8d33#diff-50ae6004c985283932947a46f4d0ca85)
