### ISSUE TITLE
tour.stop does not return currentstep

### ISSUE THREAD

**Issue by mischawas** [pulsardev/vue-tour#71]
All currentsteps are passed except when the tour.stop is called.
Code:

:stop="tour.stop"

 myCallbacks: {
           onStop: this.stopTour,
}

stopTour(currentStep) {
                console.log(currentStep);
}

console.log gives:
undefined

**Comment by mmorainville** [comment]
Hi @mischawas,

Where have you written the `:stop="tour.stop"` part in your code?
Normally you should pass the `myCallbacks` object like this:

```
<v-tour name="myTour" :steps="steps" :callbacks="myCallbacks">
```

Did you try that? See https://pulsar.gitbooks.io/vue-tour/callbacks.html for more details.

**Comment by mischawas** [comment]
This is how it did it indeed.
However, I was able to get the current step by using: this.$tours.myTour.currentStep in the stopTour function.
