### ISSUE TITLE
changing width/size of the popover

### ISSUE THREAD

**Issue by chaudigv** [pulsardev/vue-tour#72]
I noticed that upon adding too much info, the popover increases in height (that's good). But it would be great if we could manipulate the width. That way the info inside would look a bit more balanced.

Below is the most parent div I could find and adding a width didn't seem to take any effect at all.
`<div data-v-aa0cbe42="" id="v-step-686b7b5e" class="v-step" x-placement="top" style="position: absolute; transform: translate3d(656px, 98px, 0px); top: 0px; left: 0px; will-change: transform;">`

It would be great if a feature like 'v-step-2-w-50' (2nd step force width to be 50) is implemented in near future.

**Comment by machr** [comment]
I've had success overriding the css with `.v-step { max-width: 420px }` in my SCSS bundle

**Comment by mmorainville** [comment]
Hi @chaudigv,

It's a good idea but we wanted to keep options at a minimum to avoid making the configuration object too bloated. For things like that the idea was as @machr suggested to simply override the CSS.
Why make it complicated when it can be as simple as editing the CSS?
