### ISSUE TITLE
Disable Scroll To Top on next step

### ISSUE THREAD

**Issue by DamienBrn** [pulsardev/vue-tour#74]
Hi,
I am currently working with Vue Tour and I would like to know if it is possible to disable the scroll top when clicking on "Next Step".
To make myself clear : when I have two elements in a view (which are both visible without scrolling) and I go to the next step, it automatically scrolls to the top to put the element in (0,0), which I don't want. 
I've been searching for a little while now and am a bit stuck.

Thank you ! 

EDIT:

I found the solution.
Issue Closed

**Comment by DamienBrn** [comment]
I am actually a bit stuck : I thought I had found the solution with `enableScrolling` but the problem is that I want to activate the scroll but without making the target element scrolling to the top. I just want the app to scroll until the element is visible by the user.

Is that possible ?

**Comment by perez0711** [comment]
Imagine that you have an object step: 
` [{target: "mytarget"}]`

You can use the following resource in your onNextStep callback:
document.

```
       let targetElement = document.querySelector (step.target);
       targetElement.scrollIntoView (false);
```
