### ISSUE TITLE
what is the best way to handle step in a modal

### ISSUE THREAD

**Issue by JungMinHur** [pulsardev/vue-tour#76]
I want my next step stick to modal dialog element but it kept tracking its display:none position, how can I fix this

**Comment by mmorainville** [comment]
Hi @JungMinHur it depends on how your modal is triggered and which element you specified as a target.
Can you show us some code samples?

**Comment by JungMinHur** [comment]
I trigger my modal component by passing show props to v-dialog and I targeted a v-subheader tag of vuetify

**Comment by mmorainville** [comment]
You can then try add a delay before going the next step using the `before` hook from vue-tour V1.5.0.
