### ISSUE TITLE
How to disable scrolling on each step?

### ISSUE THREAD

**Issue by dylanmcgowan** [pulsardev/vue-tour#77]
Hi, I want to disable the window scroll on each step. Is this possible currently? Ideally I would like to pass in as a component prop or plugin option.

**Comment by Christilut** [comment]
I just wanted to ask the same thing. It keep scrolling down even though the tour target fits on screen already which I find annoying behavior

Any way to disable this? Or even better, dont scroll unless target is outside viewport

**Comment by Christilut** [comment]
Okay I had to dig through the source for this but the option does exist. Just add this to every tour step and it won't scroll there:

```
      params: {
        enableScrolling: false
      }
````

**Comment by dylanmcgowan** [comment]
Nice, thanks for digging man! Wish you could pass it in once (as a prop on the tour component) instead of a million times in the steps though. 

But I agree, scrolling no matter what is a poor UX, and is quite jarring when the element you're highlighting is in plain sight on the page.

**Comment by robinp** [comment]
@dylanmcgowan data is code is code is data.

```
function procSteps(steps) {
  return _.map(steps, function(s) {  // note: _ is lodash
    return {
      ...s,   // node: ES6 spread operator
      params: {
        enableScrolling: false,
      },
    };
  });
}

... steps: procSteps([ ... ])
```

**Comment by IsmaOrdas** [comment]
Thanks for the help. Agree, would be better to be able to disable scroll globally and/or for a whole group of steps, and not only individually.

**Comment by mbokil** [comment]
Is there any way to control the placement of the steps? I want to place the steps to the left or right of an element and it seems to appear in the center. Really need top, bottom, left, right.

**Comment by fonfon** [comment]
It'd be great to document all available options of a step in the wiki, e.g. on https://github.com/pulsardev/vue-tour/wiki/Features - `enableScrolling` (and maybe other options) are not described in the README.md file or in the wiki.

**Comment by HZooly** [comment]
You're right @fonfon! It's in the Wiki now https://github.com/pulsardev/vue-tour/wiki/Features#disable-scroll-between-steps
