### ISSUE TITLE
How to configure it on Nuxt?

### ISSUE THREAD

**Issue by Segueidx** [pulsardev/vue-tour#78]
Hi, i'm currently using Nuxt and i can't setting up this plugin to work with, i really hope it can be used and help me on it.

**Comment by mmorainville** [comment]
Hi @Segueidx,

Vue-tour is a simple Vue plugin so you can check the Nuxt.js documentation about using plugins: https://fr.nuxtjs.org/guide/plugins/

It should work as expected.

**Comment by Segueidx** [comment]
HI @mmorainville , thanks for your answer but i tried that and it simply still not working, strange things happens xD, i think that its a problem with the app variable, please check it, here is my code:

https://codesandbox.io/s/vue-tour-live-gdvnf

**Comment by pasDamola** [comment]
Hi @Segeuidx

Change your vue-tour.js file to look like this
import Vue from 'vue';
import VueTour from 'vue-tour';
import 'vue-tour/dist/vue-tour.css';


Vue.use(VueTour)

This should work

**Comment by mcormackalan** [comment]
@pasDamola This works perfectly with Nuxt.

**Comment by max888** [comment]
One thing to note @Segueidx is when you call `this.$tours.myTour.start();` make sure it is in the `mounted()' lifecycle hook or a later function.

I was trying to call it in `created()` and it was not working as `$tours` was undefined at this moment. Might be a nuxt thing.

Anyway, it should work :)

**Comment by abarkhurst** [comment]
> One thing to note @Segueidx is when you call `this.$tours.myTour.start();` make sure it is in the `mounted()' lifecycle hook or a later function.
> 
> I was trying to call it in `created()` and it was not working as `$tours` was undefined at this moment. Might be a nuxt thing.
> 
> Anyway, it should work :)

if you have the plugin set to be client only (no ssr) than it will not be available in the `created()` hook as this created occurs server-side

**Comment by RajOfficeTroops** [comment]
This still doesn't work:
`TypeError: this.$refs.myTour.start is not a function`

I'm using nuxt to configure the plugin, even tried to transpile the plugin in the build block in `nuxt-config.js`.

My `plugins/vue-tour-client.js`:

`import Vue from 'vue'
import VueTour from 'vue-tour'

Vue.component('VueTour', VueTour)`

This is how most of the plugins work but not working for Vue Tour.

**Comment by HZooly** [comment]
What do you mean by "doesn't work"?

**Comment by RajOfficeTroops** [comment]
The error I'm facing is `TypeError: this.$refs.myTour.start is not a function`

I have checked that the component VueTour renders a `v-tour` element on the DOM, so it's safe to say that it gets rendered properly.

However, the tour doesn't start even on `mounted()` block or in an `on click event`.

Also `Object.getOwnPropertyNames` doesn't include `start` to be a property.

**Comment by mmorainville** [comment]
Hi @RajOfficeTroops,

You should use  `this.$tours.myTour.start()` instead of `this.$refs.myTour.start()` otherwise you're juste targeting the DOM element rendered by the `v-tour` component and not a proper tour object.

**Comment by RajOfficeTroops** [comment]
`this.$tours` return `[]`. Seems the component isn't registered properly?

**Comment by mmorainville** [comment]
Do you have somewhere in a template this line:
`<v-tour name="myTour" :steps="steps"></v-tour>`?

And are you sure it is triggered/visible? Are you in a mounted hook when you console.log `this.$tours` ?

**Comment by rhnchn9** [comment]
> This still doesn't work:
> `TypeError: this.$refs.myTour.start is not a function`
> 
> I'm using nuxt to configure the plugin, even tried to transpile the plugin in the build block in `nuxt-config.js`.
> 
> My `plugins/vue-tour-client.js`:
> 
> ```
> import VueTour from 'vue-tour'
> 
> Vue.component('VueTour', VueTour)```
> 
> This is how most of the plugins work but not working for Vue Tour.
> ```

You should use ```Vue.use(VueTour)``` in place of ```Vue.component('VueTour', VueTour)```. VueTour is exported as a vue plugin, not a vue component.
