### ISSUE TITLE
CDN Support 

### ISSUE THREAD

**Issue by DelfsEngineering** [pulsardev/vue-tour#80]
Would it be possible to have CDN support and the component auto-installs?
This would be great for integrating to existing apps easily.

**Comment by mmorainville** [comment]
Hi @DelfsEngineering,

Doesn't services like UNPKG already handle this? I just tested it and it seems to work ok with vue-tour:

```html
<script src="https://unpkg.com/vue-tour@1.1.0/dist/vue-tour.umd.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/vue-tour@1.1.0/dist/vue-tour.css">
```

**Comment by DelfsEngineering** [comment]
Thanks but does it auto install?

**Comment by mmorainville** [comment]
Yes thanks to this bit of code in main.js (https://github.com/pulsardev/vue-tour/blob/master/src/main.js):

```
if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(VueTour)
}
```
