### ISSUE TITLE
Calling nextStep in onNextStep causes a loop

### ISSUE THREAD

**Issue by nviitala** [pulsardev/vue-tour#82]
`if (this.currentStep < this.numberOfSteps - 1 && this.currentStep !== -1) {
        this.customCallbacks.onNextStep(this.currentStep)
        this.currentStep++
      }`
Should be
`if (this.currentStep < this.numberOfSteps - 1 && this.currentStep !== -1) {
        this.currentStep++;
        this.customCallbacks.onNextStep(this.currentStep-1);
      }`

Otherwise it will go to a loop, since the currentStep stays the same, before reaching the next step.

This happens in a situation if we want to check in onNextStep eg if currentStep === X and some other condition matches => skip to the next step => loops forever.

**Comment by shawnhind** [comment]
This is happening to me.  I wanted to skip a step if a certain condition is met (element not on screen) so in my onNextStep callback I check a condition and then call nextStep but this is always causing an infinite loop if nextStep is ever called even once.

**Comment by mmorainville** [comment]
Hi, is the problem still happening in the last vue-tour version? The code has changed at this level recently.
