### ISSUE TITLE
Support for async

### ISSUE THREAD

**Issue by buwilliams** [pulsardev/vue-tour#85]
Currently for complex single-page applications, there is no way to handle async UI operations between steps. For example, on step one, I want to show a menu but on step two, I want to hide that menu and open a modal. There needs to be a way to do additional UI setup work between steps.

I've created a [pull request](https://github.com/pulsardev/vue-tour/pull/84) which addresses this issue by allowing users to optionally specify a `before()` callback on each step.

I've created an issue for this since it seems that issues are responded to more frequently. I apologize if this was unnecessary.

**Comment by mmorainville** [comment]
PR has been merged: https://github.com/pulsardev/vue-tour/pull/84.
