### ISSUE TITLE
position: Static header make the tips shifted

### ISSUE THREAD

**Issue by sandroden** [pulsardev/vue-tour#90]
I'm using quasar with a fixed header. I read other issues that suggested that that's a problem but I have not understood if there's a solution. If needed I can create a codesandbox.io to show the result.

Thanks in advance

**Comment by mmorainville** [comment]
Hi @sandroden,

In which case is it a problem? A codesandbox could indeed help.
If it's because of the z-index you can try to increase it.

**Comment by sandroden** [comment]
Sorry @mmorainville  for not being clear in my post. 
I'm talking about (dis)placement of tooltip in the sidebar
[Here you can find a complete codesandbox](https://codesandbox.io/s/codesandbox-app-gqfe2) example that is really much worse than what I have in my setup...
If youre not familiar with Quasar setup, let me point out that you won't find a `main.js` and inizialization is made within `boot/vue-tour.js` declared in `quasar.conf.js`.
In my [real setup](https://wikidattica.org) I have a vertical shift (that I corrected cheating with the target) while here I also see a horizontal shift.

**Comment by Sweetyy** [comment]
Same problem for me with Quasar and fixed elements in the top navbar.

**Comment by louisameline** [comment]
Same issue. Basically, vue-tour scrolls down to put the target at the top of the window. Unfortunately, there is a header there. We should be able to specify some vertical offset that would be taken into account for scrolling.

![image](https://user-images.githubusercontent.com/371814/72751673-820ef780-3bc0-11ea-9c1e-9796316ec3c2.png)

**Comment by mreall** [comment]
I have a similar problem, although I'm not using Quasar. I have a fixed header that stays at the top of the page when the user scrolls.  vue-tour is offset from where the actual element is.
![offset-tour](https://user-images.githubusercontent.com/15823671/80016284-8507d580-8498-11ea-8451-8629b4802b84.png)

**Comment by mreall** [comment]
I did a quick experiment and it looks like this issue would be fixed by upgrading to popper 2.  The upgrade doesn't seem to be very invasive, either.

**Comment by HZooly** [comment]
Thanks for your analysis. Unfortunately, we're not going to upgrade Popper version in the current major Vue Tour version: there are some breaking changes between Popper and Popper 2, we don't want to introduce breaking changes in Vue Tour 1.x.

See proposals here : https://github.com/pulsardev/vue-tour/issues/103

**Comment by mmorainville** [comment]
Hi,

Vue Tour v2.x is out and now uses Popper v2.x so this should fix this issue.
