### ISSUE TITLE
Disable skip tour

### ISSUE THREAD

**Issue by chrstngyn** [pulsardev/vue-tour#93]
How can I disable the "skip tour" feature?

**Comment by HZooly** [comment]
@chrstngyn, as far as I know, there is no option for hiding *skip tour* button. Could be a good enhancement! @mmorainville

**Comment by mmorainville** [comment]
Hi @chrstngyn,

There is Indeed no option to "simply" disable buttons, but you can totally use the template customization feature as follows:

```
<v-tour name="myTour" :steps="steps">
  <template slot-scope="tour">
    <transition name="fade">
      <v-step
        v-if="tour.currentStep === index"
        v-for="(step, index) of tour.steps"
        :key="index"
        :step="step"
        :previous-step="tour.previousStep"
        :next-step="tour.nextStep"
        :stop="tour.stop"
        :is-first="tour.isFirst"
        :is-last="tour.isLast"
        :labels="tour.labels"
      >
        <template>
          <div slot="actions">
            <button @click="tour.previousStep" class="btn btn-primary">Previous step</button>
            <button @click="tour.nextStep" class="btn btn-primary">Next step</button>
          </div>
        </template>
      </v-step>
    </transition>
  </template>
</v-tour>
```

This is will allow you to have only a Previous and Next button for example. But I admit it's a bit verbose.

**Comment by chrstngyn** [comment]
@mmorainville 

I tried adding this piece of code to disable skip tour, but it throws this error:

`The 'undefined' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'.`

and also

`Property or method "tour" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. `

I've imported VueTour as well.

![vue-tour](https://user-images.githubusercontent.com/8737685/68512189-f0d0eb80-0234-11ea-9089-ef7124ce17c2.png)

**Comment by chrstngyn** [comment]
May have found a possible solution: https://medium.com/js-dojo/vue-typescript-handling-types-for-injected-properties-73d9ddb50b35

I have created a vue-tour.d.ts file in my root folder. Going to modify according to the article above and see what happens.

**Comment by mmorainville** [comment]
Hi @chrstngyn,

An option to disable/enable buttons via a the tour configuration has been added in v1.3.0 thanks to a PR by @guastallaigor.
